### ISSUE TITLE
still active?

### ISSUE THREAD

**Issue by cevhyruz** [nkakouros-original/bash-autopairs#1]
Hi!, Is this project still active? It seems to be incomplete, I would like to send some PR if that's okay.

**Comment by nkakouros** [comment]
It is in a "works-for-me-with-a-few-headaches" state. Feel free to submit a PR!

**Comment by cevhyruz** [comment]
Sorry for the delay. I have submitted a PR.

Here are some features I think should be added:

* add a unit test suite. I propose https://github.com/bats-core/bats-core since this is purely for bash anyway.
* smart spacing. for pairs like `(`, `[` and `{` hitting spacebar will insert spaces. so instead of  `( |)` it will be like this `( | )`

what do you think?

**Comment by nkakouros** [comment]
These are nice features to have indeed. We could add them little by little. I believe the top priorities we should keep in mind should be to:

- keep the code simple to understand
- keep the code as fast as possible.

So, in adding these features, we have to think how to implement them in a minimalist approach. And one TODO to carry out is to review the current implementation for unnecessary code, opportunities to simplify, etc.

**Comment by cevhyruz** [comment]
>  And one TODO to carry out is to review the current implementation for unnecessary code, opportunities to simplify, etc.

I agree. I'm gonna experiment with the source code a bit then will open an issue for possible simplification.

**Comment by nkakouros** [comment]
I added the `( | )` feature (useful for formatting subshells, arithmetic operations, etc). It also works for `[ | ]` (useful for conditionals). And the `{ | }` case, useful for formatting blocks. If you try it out, let me know.

Other than some edge cases with unbalanced pairs (which the script may not be able to do much anyway) and multiline editing that would be out of scope (I think), the project should be feature complete now. I don't know what else could be added that made sense.

**Comment by cevhyruz** [comment]
Thanks!
