### ISSUE TITLE
Readline seldom flickers

### ISSUE THREAD

**Issue by cevhyruz** [nkakouros-original/bash-autopairs#3]
Readline sometimes flickers when using the bindings from autopairs. Cant really figure out why?

**Comment by nkakouros** [comment]
This seems like a performance issue. Do you run a lot of things in your bashrc? Also, what is the output of `bind -q magic-space`?

**Comment by cevhyruz** [comment]
> what is the output of bind -q magic-space?

magic space is not bound to any keys
also I can reproduce with `bash --norc`.

It always triggers on `space`, sometimes on pairs
also pressing and holding any auto pair keybindings results in a flicker.

**Comment by nkakouros** [comment]
Right, I could reproduce this. This is clearly a performance issue. I don't know if it is indeed an "issue", as there will always be some overhead in calling and executing the bindings. I will leave this open as a todo to at some point go through the code for performance improvements.

**Comment by cevhyruz** [comment]
@nkakouros 
From the author of the [ble.sh](https://github.com/akinomyoga/ble.sh/)

> By default, Bash (Readline) erases the command line before calling the
`bind -x` commands and renders the command line again after the `bind
-x` command is finished. 

> These terminal renderings by Readline are all
performed by outputting terminal control sequences and characters to
stderr (fd 2)

We really have no way to fix the issue, unless we redirect `fd 2` of bash itself to `/dev/null`.
However, doing so will also disable the following:
* prompt
* character printing (while typing)

**Comment by nkakouros** [comment]
Good insight, thanks @cevhyruz. Then I will close this issue.

**Comment by cevhyruz** [comment]
using [QTerminal 1.4.0](https://github.com/lxqt/qterminal), the flickering is gone, so I guess this is about how different terminal emulators handle the drawing of prompt and parsing control sequences.
