### ISSUE TITLE
Space will delete the pair

### ISSUE THREAD

**Issue by tomoum** [nkakouros-original/bash-autopairs#4]
Hi, Thank you for creating this awesome tool. I am seeing this issue where if I type a space the second pair that has been added will be overwritten. Thought id share. It kinda makes this tool obsolete for me since I rarely create a bracket pair without inserting a space and I have to add that in manually anyway because of this issue. 

thanks.

**Comment by nkakouros** [comment]
Could you add some screenshot or preferably a video showing what you experience? Also add `bash --version`. 

This is what I get if on an empty prompt I type <kbd>(</kbd>+<kbd>Spacebar</kbd>:

<img width="84" alt="Screenshot 2023-04-13 at 00 08 50" src="https://user-images.githubusercontent.com/11805218/231585572-76431f4c-4915-49c4-aa90-10b221a95b35.png">

Have you tried with an empty `.bashrc` that just includes this extension?

**Comment by nkakouros** [comment]
Fixed in latest commit (f16eb77)
